sudo: required
services:
  - docker

before_install:
  - docker build -t sidyjw/docker-react --target dev .

script:
  - docker run --rm -e CI=true sidyjw/docker-react run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-sa-east-1-510987755050"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
