language: node
sudo: required
services:
  - docker

before_install:
  - docker build -t sidyjw/docker-react --target dev .

script:
  - docker run --rm -e CI=true sidyjw/docker-react run test -- --coverage
